// <auto-generated />
using System;
using GraduateProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateProject.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240502170446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduateProject.Domain.Core.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7543ddb1-c158-41b9-b9b2-76ac27c00994"),
                            Description = "Description of a book.",
                            Name = "Tom",
                            Price = 37
                        },
                        new
                        {
                            Id = new Guid("7059a1b6-2b44-4deb-a66d-3d133b5d9582"),
                            Description = "Description of a book.",
                            Name = "Bob",
                            Price = 41
                        },
                        new
                        {
                            Id = new Guid("ef0399a0-ae05-4dd7-9d90-4ffb7b174e20"),
                            Description = "Description of a book.",
                            Name = "Sam",
                            Price = 24
                        });
                });

            modelBuilder.Entity("GraduateProject.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62731a5f-dabe-427e-ac94-4e2ab32e8429"),
                            Login = "qwe",
                            Password = "qwe"
                        },
                        new
                        {
                            Id = new Guid("e63ad5fe-005e-4854-8d2b-f2a799426efa"),
                            Login = "asd",
                            Password = "asd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
